language: python
python:
  - "3.6"
  #- "3.7" not yet available in travis
addons:
  sonarcloud:
    organization: "kmindi-github" # the key of the org you chose at step #3
cache:
  directories:
  - "$HOME/.sonar/cache"
install:
  - pip install -r requirements.txt
script:
  - pytest --junitxml=xunitresult.xml --cov=. --cov-report=xml
  - sonar-scanner
