language: python
matrix:
    include:
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
addons:
  sonarcloud:
    organization: "kmindi-github" # the key of the org you chose at step #3
cache:
  directories:
  - "$HOME/.sonar/cache"
  - "$HOME/.cache/pip"
install:
  - pip install -r requirements.txt
script:
  - pylint src
  - pytest --junitxml=xunitresult.xml --cov=. --cov-report=xml
  - sonar-scanner
