language: python
python:
  - "2.6"
  - "2.7"
  # - "3.3" does not work because cryptography does not work in 3.3
  - "3.4"
  - "3.5"
  - "3.6"
  # command to install dependencies
addons:
  sonarcloud:
    organization: "kmindi-github" # the key of the org you chose at step #3
cache:
  directories:
  - "$HOME/.sonar/cache"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python cryptoexamples/example.py
  - sonar-scanner
